name: Deploy to S3 and EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2  # 서울 리전

      - name: Sync files to S3
        run: |
          aws s3 sync ./ s3://ssalbtibucket/ --delete

      - name: Create PEM file
        run: |
          echo "${{ secrets.PEM_FILE }}" | tr -d '\r' > /tmp/SsalBTI-KeyPair.pem
          chmod 400 /tmp/SsalBTI-KeyPair.pem

      - name: Connect to EC2 and deploy
        run: |
          ssh -o StrictHostKeyChecking=no -i /tmp/SsalBTI-KeyPair.pem ec2-user@43.202.66.204 "aws s3 sync s3://ssalbtibucket/ /path/to/local/directory"